"""R67: the ambient previews must not fabricate what the device draws.

Split from test_round6_layout_exposure_phase2.py (500-line cap). These pin the
honesty property, which is the thing that would have made the ambient bug
visible: four of the five modes are generated by the DEVICE from a palette we do
not have, and the tiles used to show invented colours for them.
"""
from pathlib import Path

WEB_UI = Path(__file__).parent.parent / "divoom_gui" / "web_ui"


def test_ambient_previews_do_not_fabricate_device_colours():
    """R67: four of the five ambient modes are drawn by the DEVICE.

    The tiles used to show invented colour blocks for them — a red-and-blue SVG
    for "Plants", flat green for "Sleeping", translucent orange for
    "No-Mosquito". Nothing produced those colours. That fabrication is why the
    ambient bug reached the user as "the rest are green/magenta" instead of "the
    mode never reached the device": a confident picture with no connection to
    the panel made a dead feature look merely wrong.

    Only Plain Colour is knowable in the browser, because it is the colour the
    user picked. The rest must say the device draws them.
    """
    js = (WEB_UI / "channels_grids.js").read_text(encoding="utf-8")

    block = js[js.index("const AMBIENT_PREVIEWS"):js.index("let selectedAmbientMode")]

    # Plain still shows a real colour — it is the one we genuinely know.
    assert "ambient-preview plain" in block

    # The device-generated modes must not carry invented colours.
    for invented in ("#ff0000", "#0000ff", "#33cc33", "255, 165, 0"):
        assert invented not in block, (
            f"{invented} is a fabricated colour for a device-generated effect")

    assert block.count("deviceEffectTile") == 4, (
        "modes 1-4 should each use the honest device-effect tile "
        "(the helper is DEFINED above this block, so only its four uses are here)")

def test_active_ambient_mode_reflects_the_device_not_the_click():
    """A tile must highlight only when the device ACCEPTED the mode.

    LAN cannot express modes 1-4 at all, so highlighting on click would report a
    success the device never gave.
    """
    js = (WEB_UI / "channels_grids.js").read_text(encoding="utf-8")

    assert "markActiveAmbientMode(res ? modeType : null)" in js, (
        "the active marker must be driven by the apply RESULT, not the click")
