"""Regression tests for tools/check_no_allow.py.

The gate turned CI red on a doc comment that EXPLAINED why a field was named
`_file` "rather than carrying an #[allow(dead_code)]" — it matched its own
rationale. Same defect class as check_positional_args.py (fixed in 0379194):
source text does not distinguish an attribute from prose quoting one.

Both directions are pinned: the gate must ignore comments, and it must still
bite on a real attribute. A gate that only ever passes is not a gate.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

check_no_allow = pytest.importorskip("check_no_allow")


def _scan_text(tmp_path: Path, body: str) -> list[str]:
    """Run the gate's scanner over one synthetic source file."""
    src = tmp_path / "src"
    src.mkdir(exist_ok=True)
    f = src / "sample.rs"
    f.write_text(body)
    return check_no_allow._scan([f])


def test_comment_mentioning_allow_is_not_a_violation(tmp_path):
    """The exact shape that reddened CI on socket_bind.rs."""
    hits = _scan_text(
        tmp_path,
        "/// The field is named `_file` rather than carrying an\n"
        "/// `#[allow(dead_code)]`: nothing reads it, and that is the point.\n"
        "pub struct StartupLock {\n"
        "    _file: std::fs::File,\n"
        "}\n",
    )
    assert hits == [], f"prose about #[allow] is not an #[allow]: {hits}"


def test_block_comment_mentioning_allow_is_not_a_violation(tmp_path):
    hits = _scan_text(tmp_path, "/* historical: this used to be #[allow(unused)] */\nfn f() {}\n")
    assert hits == []


def test_a_real_attribute_still_fails(tmp_path):
    """Calibration: prove the instrument can produce the failing answer."""
    hits = _scan_text(tmp_path, "#[allow(dead_code)]\nfn f() {}\n")
    assert len(hits) == 1, "a genuine #[allow] must still be caught"
    assert "sample.rs:1" in hits[0]


def test_inner_attribute_still_fails(tmp_path):
    hits = _scan_text(tmp_path, "#![allow(clippy::all)]\n")
    assert len(hits) == 1


def test_reported_line_number_survives_stripping(tmp_path):
    """Comment blanking preserves offsets, so the reported line must be exact."""
    hits = _scan_text(
        tmp_path,
        "// a comment mentioning #[allow(x)]\n"
        "fn a() {}\n"
        "\n"
        "#[allow(dead_code)]\n"
        "fn b() {}\n",
    )
    assert len(hits) == 1
    assert hits[0].endswith(":4: #[allow(dead_code)]"), hits[0]


def test_expect_is_still_permitted(tmp_path):
    """`#[expect]` errors when its lint stops firing, so it cannot rot."""
    assert _scan_text(tmp_path, "#[expect(dead_code)]\nfn f() {}\n") == []


def test_generated_files_are_exempt(tmp_path):
    assert _scan_text(tmp_path, "// @generated by prost\n#[allow(dead_code)]\nfn f() {}\n") == []


def test_gate_passes_on_current_tree():
    r = subprocess.run(
        [sys.executable, "tools/check_no_allow.py"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    assert r.returncode == 0, r.stdout + r.stderr
