//! Command name -> protocol id, GENERATED from `divoom_lib.models.COMMANDS`.
//! Do not edit by hand; regenerate via `scripts/codegen/gen_commands.py`.
//! @generated

/// Every command NAME and its protocol id: data, not a match, so the
/// table is the size of the protocol and no function grows with it.
pub const COMMANDS: &[(&str, u8)] = &[
    ("set volume", 0x08),
    ("set playstate", 0x0a),
    ("set gif speed", 0x16),
    ("set game ctrl info", 0x17),
    ("set date time", 0x18),
    ("app send eq gif", 0x1b),
    ("set game ctrl key up info", 0x21),
    ("set keyboard", 0x23),
    ("set hot", 0x26),
    ("send hotctrl", 0x85),
    ("send hot file list", 0x9b),
    ("hot update file info", 0x9d),
    ("hot send file data", 0x9e),
    ("hot pause file send", 0x9f),
    ("request new file info", 0xf7),
    ("set blue password", 0x27),
    ("sand paint ctrl", 0x34),
    ("pic scan ctrl", 0x35),
    ("drawing mul pad ctrl", 0x3a),
    ("drawing big pad ctrl", 0x3b),
    ("set temp type", 0x2b),
    ("set time type", 0x2c),
    ("set lightness", 0x32),
    ("set sleeptime", 0x40),
    ("set sleep scene", 0x41),
    ("get alarm time", 0x42),
    ("set alarm", 0x43),
    ("set light pic", 0x44),
    ("set image", 0x44),
    ("set animation frame", 0x49),
    ("set light mode", 0x45),
    ("set channel light", 0x45),
    ("get light mode", 0x46),
    ("app need get music list", 0x47),
    ("set light phone gif", 0x49),
    ("set alarm gif", 0x51),
    ("set temp unit", 0x4c),
    ("set android ancs", 0x50),
    ("set boot gif", 0x52),
    ("get memorial time", 0x53),
    ("set memorial", 0x54),
    ("set memorial gif", 0x55),
    ("set time manage info", 0x56),
    ("set time manage ctrl", 0x57),
    ("drawing pad ctrl", 0x58),
    ("get device temp", 0x59),
    ("drawing pad exit", 0x5a),
    ("drawing mul encode single pic", 0x5b),
    ("drawing mul encode pic", 0x5c),
    ("send net temp", 0x5d),
    ("send net temp disp", 0x5e),
    ("set temp", 0x5f),
    ("send current temp", 0x5f),
    ("set radio frequency", 0x61),
    ("drawing mul encode gif play", 0x6b),
    ("drawing encode movie play", 0x6c),
    ("drawing mul encode movie play", 0x6d),
    ("drawing ctrl movie play", 0x6e),
    ("drawing mul pad enter", 0x6f),
    ("get tool info", 0x71),
    ("set tool", 0x72),
    ("get net temp disp", 0x73),
    ("set brightness", 0x74),
    ("set device name", 0x75),
    ("get device name", 0x76),
    ("get sd music list total num", 0x7d),
    ("set alarm vol ctrl", 0x82),
    ("set song dis ctrl", 0x83),
    ("set light phone word attr", 0x87),
    ("set text content", 0x86),
    ("send game shark", 0x88),
    ("set poweron channel", 0x8a),
    ("app new send gif cmd", 0x8b),
    ("app new user define", 0x8c),
    ("app big64 user define", 0x8d),
    ("app get user define info", 0x8e),
    ("set game", 0xa0),
    ("get sleep scene", 0xa2),
    ("set sleep scene listen", 0xa3),
    ("set scene vol", 0xa4),
    ("set alarm listen", 0xa5),
    ("set alarm vol", 0xa6),
    ("set sound ctrl", 0xa7),
    ("get sound ctrl", 0xa8),
    ("set auto power off", 0xab),
    ("get auto power off", 0xac),
    ("set sleep color", 0xad),
    ("set sleep light", 0xae),
    ("set user gif", 0xb1),
    ("set low power switch", 0xb2),
    ("get low power switch", 0xb3),
    ("get sd music info", 0xb4),
    ("set sd music info", 0xb5),
    ("modify user gif items", 0xb6),
    ("set rhythm gif", 0xb7),
    ("set sd music position", 0xb8),
    ("set sd music play mode", 0xb9),
    ("set poweron voice vol", 0xbb),
    ("set design", 0xbd),
    ("set work mode", 0x05),
    ("get sd music list", 0x07),
    ("get volume", 0x09),
    ("get play status", 0x0b),
    ("set sd play music id", 0x11),
    ("set sd last next", 0x12),
    ("send sd list over", 0x14),
    ("send sd status", 0x15),
    ("get sd play name", 0x06),
    ("get work mode", 0x13),
];

/// Number of known command NAMES, checked by
/// `tests/test_command_model_parity.py` against `len(COMMANDS)`.
pub const COMMAND_COUNT: usize = 109;

/// Number of distinct protocol ids, which is fewer than the name count:
/// four ids are spelled two ways.
pub const COMMAND_ID_COUNT: usize = 105;

// The name lookups moved to `command_names` when the model was split out
// (they need the type), and they are RE-EXPORTED here rather than
// moved: `commands::command_id` was this crate's public spelling and an
// integration test imports it. Both paths now route through the enum, so
// a name and its id cannot come from different sources.
pub use crate::command_names::{command, command_id};
