//! Name <-> command indexes, GENERATED from `divoom_lib.models.COMMANDS`.
//! Do not edit by hand; regenerate via `scripts/codegen/gen_commands.py`.
//! @generated

use crate::command_model::Command;

/// One entry per command: the canonical name and the command it names.
/// The same table `Command::name` reads, exposed so a caller can walk
/// names and commands together without going through the aliases.
pub const CANONICAL_NAMES: &[(&str, Command)] = &[
    ("set volume", Command::SetVolume),
    ("set playstate", Command::SetPlaystate),
    ("set gif speed", Command::SetGifSpeed),
    ("set game ctrl info", Command::SetGameCtrlInfo),
    ("set date time", Command::SetDateTime),
    ("app send eq gif", Command::AppSendEqGif),
    ("set game ctrl key up info", Command::SetGameCtrlKeyUpInfo),
    ("set keyboard", Command::SetKeyboard),
    ("set hot", Command::SetHot),
    ("send hotctrl", Command::SendHotctrl),
    ("send hot file list", Command::SendHotFileList),
    ("hot update file info", Command::HotUpdateFileInfo),
    ("hot send file data", Command::HotSendFileData),
    ("hot pause file send", Command::HotPauseFileSend),
    ("request new file info", Command::RequestNewFileInfo),
    ("set blue password", Command::SetBluePassword),
    ("sand paint ctrl", Command::SandPaintCtrl),
    ("pic scan ctrl", Command::PicScanCtrl),
    ("drawing mul pad ctrl", Command::DrawingMulPadCtrl),
    ("drawing big pad ctrl", Command::DrawingBigPadCtrl),
    ("set temp type", Command::SetTempType),
    ("set time type", Command::SetTimeType),
    ("set lightness", Command::SetLightness),
    ("set sleeptime", Command::SetSleeptime),
    ("set sleep scene", Command::SetSleepScene),
    ("get alarm time", Command::GetAlarmTime),
    ("set alarm", Command::SetAlarm),
    ("set light pic", Command::SetLightPic),
    ("set animation frame", Command::SetAnimationFrame),
    ("set light mode", Command::SetLightMode),
    ("get light mode", Command::GetLightMode),
    ("app need get music list", Command::AppNeedGetMusicList),
    ("set alarm gif", Command::SetAlarmGif),
    ("set temp unit", Command::SetTempUnit),
    ("set android ancs", Command::SetAndroidAncs),
    ("set boot gif", Command::SetBootGif),
    ("get memorial time", Command::GetMemorialTime),
    ("set memorial", Command::SetMemorial),
    ("set memorial gif", Command::SetMemorialGif),
    ("set time manage info", Command::SetTimeManageInfo),
    ("set time manage ctrl", Command::SetTimeManageCtrl),
    ("drawing pad ctrl", Command::DrawingPadCtrl),
    ("get device temp", Command::GetDeviceTemp),
    ("drawing pad exit", Command::DrawingPadExit),
    (
        "drawing mul encode single pic",
        Command::DrawingMulEncodeSinglePic,
    ),
    ("drawing mul encode pic", Command::DrawingMulEncodePic),
    ("send net temp", Command::SendNetTemp),
    ("send net temp disp", Command::SendNetTempDisp),
    ("set temp", Command::SetTemp),
    ("set radio frequency", Command::SetRadioFrequency),
    (
        "drawing mul encode gif play",
        Command::DrawingMulEncodeGifPlay,
    ),
    ("drawing encode movie play", Command::DrawingEncodeMoviePlay),
    (
        "drawing mul encode movie play",
        Command::DrawingMulEncodeMoviePlay,
    ),
    ("drawing ctrl movie play", Command::DrawingCtrlMoviePlay),
    ("drawing mul pad enter", Command::DrawingMulPadEnter),
    ("get tool info", Command::GetToolInfo),
    ("set tool", Command::SetTool),
    ("get net temp disp", Command::GetNetTempDisp),
    ("set brightness", Command::SetBrightness),
    ("set device name", Command::SetDeviceName),
    ("get device name", Command::GetDeviceName),
    (
        "get sd music list total num",
        Command::GetSdMusicListTotalNum,
    ),
    ("set alarm vol ctrl", Command::SetAlarmVolCtrl),
    ("set song dis ctrl", Command::SetSongDisCtrl),
    ("set light phone word attr", Command::SetLightPhoneWordAttr),
    ("set text content", Command::SetTextContent),
    ("send game shark", Command::SendGameShark),
    ("set poweron channel", Command::SetPoweronChannel),
    ("app new send gif cmd", Command::AppNewSendGifCmd),
    ("app new user define", Command::AppNewUserDefine),
    ("app big64 user define", Command::AppBig64UserDefine),
    ("app get user define info", Command::AppGetUserDefineInfo),
    ("set game", Command::SetGame),
    ("get sleep scene", Command::GetSleepScene),
    ("set sleep scene listen", Command::SetSleepSceneListen),
    ("set scene vol", Command::SetSceneVol),
    ("set alarm listen", Command::SetAlarmListen),
    ("set alarm vol", Command::SetAlarmVol),
    ("set sound ctrl", Command::SetSoundCtrl),
    ("get sound ctrl", Command::GetSoundCtrl),
    ("set auto power off", Command::SetAutoPowerOff),
    ("get auto power off", Command::GetAutoPowerOff),
    ("set sleep color", Command::SetSleepColor),
    ("set sleep light", Command::SetSleepLight),
    ("set user gif", Command::SetUserGif),
    ("set low power switch", Command::SetLowPowerSwitch),
    ("get low power switch", Command::GetLowPowerSwitch),
    ("get sd music info", Command::GetSdMusicInfo),
    ("set sd music info", Command::SetSdMusicInfo),
    ("modify user gif items", Command::ModifyUserGifItems),
    ("set rhythm gif", Command::SetRhythmGif),
    ("set sd music position", Command::SetSdMusicPosition),
    ("set sd music play mode", Command::SetSdMusicPlayMode),
    ("set poweron voice vol", Command::SetPoweronVoiceVol),
    ("set design", Command::SetDesign),
    ("set work mode", Command::SetWorkMode),
    ("get sd music list", Command::GetSdMusicList),
    ("get volume", Command::GetVolume),
    ("get play status", Command::GetPlayStatus),
    ("set sd play music id", Command::SetSdPlayMusicId),
    ("set sd last next", Command::SetSdLastNext),
    ("send sd list over", Command::SendSdListOver),
    ("send sd status", Command::SendSdStatus),
    ("get sd play name", Command::GetSdPlayName),
    ("get work mode", Command::GetWorkMode),
];

/// Every command NAME with the command it resolves to, aliases included.
/// The name -> command direction is a scan, not a match, because the
/// ids repeat and a match on them would silently drop three names.
pub const COMMAND_NAMES: &[(&str, Command)] = &[
    ("set volume", Command::SetVolume),
    ("set playstate", Command::SetPlaystate),
    ("set gif speed", Command::SetGifSpeed),
    ("set game ctrl info", Command::SetGameCtrlInfo),
    ("set date time", Command::SetDateTime),
    ("app send eq gif", Command::AppSendEqGif),
    ("set game ctrl key up info", Command::SetGameCtrlKeyUpInfo),
    ("set keyboard", Command::SetKeyboard),
    ("set hot", Command::SetHot),
    ("send hotctrl", Command::SendHotctrl),
    ("send hot file list", Command::SendHotFileList),
    ("hot update file info", Command::HotUpdateFileInfo),
    ("hot send file data", Command::HotSendFileData),
    ("hot pause file send", Command::HotPauseFileSend),
    ("request new file info", Command::RequestNewFileInfo),
    ("set blue password", Command::SetBluePassword),
    ("sand paint ctrl", Command::SandPaintCtrl),
    ("pic scan ctrl", Command::PicScanCtrl),
    ("drawing mul pad ctrl", Command::DrawingMulPadCtrl),
    ("drawing big pad ctrl", Command::DrawingBigPadCtrl),
    ("set temp type", Command::SetTempType),
    ("set time type", Command::SetTimeType),
    ("set lightness", Command::SetLightness),
    ("set sleeptime", Command::SetSleeptime),
    ("set sleep scene", Command::SetSleepScene),
    ("get alarm time", Command::GetAlarmTime),
    ("set alarm", Command::SetAlarm),
    ("set light pic", Command::SetLightPic),
    ("set image", Command::SetLightPic),
    ("set animation frame", Command::SetAnimationFrame),
    ("set light phone gif", Command::SetAnimationFrame),
    ("set light mode", Command::SetLightMode),
    ("set channel light", Command::SetLightMode),
    ("get light mode", Command::GetLightMode),
    ("app need get music list", Command::AppNeedGetMusicList),
    ("set alarm gif", Command::SetAlarmGif),
    ("set temp unit", Command::SetTempUnit),
    ("set android ancs", Command::SetAndroidAncs),
    ("set boot gif", Command::SetBootGif),
    ("get memorial time", Command::GetMemorialTime),
    ("set memorial", Command::SetMemorial),
    ("set memorial gif", Command::SetMemorialGif),
    ("set time manage info", Command::SetTimeManageInfo),
    ("set time manage ctrl", Command::SetTimeManageCtrl),
    ("drawing pad ctrl", Command::DrawingPadCtrl),
    ("get device temp", Command::GetDeviceTemp),
    ("drawing pad exit", Command::DrawingPadExit),
    (
        "drawing mul encode single pic",
        Command::DrawingMulEncodeSinglePic,
    ),
    ("drawing mul encode pic", Command::DrawingMulEncodePic),
    ("send net temp", Command::SendNetTemp),
    ("send net temp disp", Command::SendNetTempDisp),
    ("set temp", Command::SetTemp),
    ("send current temp", Command::SetTemp),
    ("set radio frequency", Command::SetRadioFrequency),
    (
        "drawing mul encode gif play",
        Command::DrawingMulEncodeGifPlay,
    ),
    ("drawing encode movie play", Command::DrawingEncodeMoviePlay),
    (
        "drawing mul encode movie play",
        Command::DrawingMulEncodeMoviePlay,
    ),
    ("drawing ctrl movie play", Command::DrawingCtrlMoviePlay),
    ("drawing mul pad enter", Command::DrawingMulPadEnter),
    ("get tool info", Command::GetToolInfo),
    ("set tool", Command::SetTool),
    ("get net temp disp", Command::GetNetTempDisp),
    ("set brightness", Command::SetBrightness),
    ("set device name", Command::SetDeviceName),
    ("get device name", Command::GetDeviceName),
    (
        "get sd music list total num",
        Command::GetSdMusicListTotalNum,
    ),
    ("set alarm vol ctrl", Command::SetAlarmVolCtrl),
    ("set song dis ctrl", Command::SetSongDisCtrl),
    ("set light phone word attr", Command::SetLightPhoneWordAttr),
    ("set text content", Command::SetTextContent),
    ("send game shark", Command::SendGameShark),
    ("set poweron channel", Command::SetPoweronChannel),
    ("app new send gif cmd", Command::AppNewSendGifCmd),
    ("app new user define", Command::AppNewUserDefine),
    ("app big64 user define", Command::AppBig64UserDefine),
    ("app get user define info", Command::AppGetUserDefineInfo),
    ("set game", Command::SetGame),
    ("get sleep scene", Command::GetSleepScene),
    ("set sleep scene listen", Command::SetSleepSceneListen),
    ("set scene vol", Command::SetSceneVol),
    ("set alarm listen", Command::SetAlarmListen),
    ("set alarm vol", Command::SetAlarmVol),
    ("set sound ctrl", Command::SetSoundCtrl),
    ("get sound ctrl", Command::GetSoundCtrl),
    ("set auto power off", Command::SetAutoPowerOff),
    ("get auto power off", Command::GetAutoPowerOff),
    ("set sleep color", Command::SetSleepColor),
    ("set sleep light", Command::SetSleepLight),
    ("set user gif", Command::SetUserGif),
    ("set low power switch", Command::SetLowPowerSwitch),
    ("get low power switch", Command::GetLowPowerSwitch),
    ("get sd music info", Command::GetSdMusicInfo),
    ("set sd music info", Command::SetSdMusicInfo),
    ("modify user gif items", Command::ModifyUserGifItems),
    ("set rhythm gif", Command::SetRhythmGif),
    ("set sd music position", Command::SetSdMusicPosition),
    ("set sd music play mode", Command::SetSdMusicPlayMode),
    ("set poweron voice vol", Command::SetPoweronVoiceVol),
    ("set design", Command::SetDesign),
    ("set work mode", Command::SetWorkMode),
    ("get sd music list", Command::GetSdMusicList),
    ("get volume", Command::GetVolume),
    ("get play status", Command::GetPlayStatus),
    ("set sd play music id", Command::SetSdPlayMusicId),
    ("set sd last next", Command::SetSdLastNext),
    ("send sd list over", Command::SendSdListOver),
    ("send sd status", Command::SendSdStatus),
    ("get sd play name", Command::GetSdPlayName),
    ("get work mode", Command::GetWorkMode),
];

/// Resolve a command NAME to the command it is, or `None` if unknown.
#[must_use]
pub fn command(name: &str) -> Option<Command> {
    COMMAND_NAMES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, cmd)| *cmd)
}

/// Resolve a command NAME to its protocol id, or `None` if unknown.
///
/// The pre-L2 spelling, kept because callers hold it: it now routes
/// through the type rather than the table, so a name and its id cannot
/// come from different sources.
#[must_use]
pub fn command_id(name: &str) -> Option<u8> {
    command(name).map(Command::id)
}
